version: 0.2

phases:
  install:   
    runtime-versions:
      runtime: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_buil
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/todo-rest-api-h2-cicd-pipeline-1.0.0.RELEASE.war
